### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by aaronk**
The "entry_points" won't work with distutils.core.setup.

### CODE REVIEW

**Comment by yarden** [comment]
Thank you for the pull request. The issue is that when I try using `setuptools`, it makes it so `pip install .` doesn't trigger compilation of the C source code. Have you run into this?

**Comment by aaronk** [comment]
Not me.  Haven't really done that much with it though.  My colleague and I just ran into the problem with the entry points.  

I supposed you could get rid of entry_points and just make the executables directly.

ajk

**Comment by yarden** [comment]
`entry_points` is supposed to be the right way to get Python executables that are "guaranteed" (if Python packaging weren't the broken affair it is) to be in the user's path.

**Comment by aaronk** [comment]
Well it seems like you'll have to decide between "pip install ." (I personally have never used this) and having executables created by entry_points.

ajk

Aaron Kitzmiller
aaron.kitzmiller@gmail.com

**Comment by yarden** [comment]
Merged.

**Pull request merged**
